### ISSUE TITLE
Crash in Debug Mode

### ISSUE THREAD

**Issue by Lassebq** [jredfox/OpenTerminal#41]
In an attempt to launch the terminal in debug mode from Eclipse the following error occurs:
```ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
shutting down OpenTerminal Launcher:2
```

**Comment by jredfox** [comment]
OpenTerminal shouldn't open a terminal in debug mode as you are suppose to use your IDE to debug it. does it work without clicking debug mode? are you on java 8 and are you using windows 10?

**Comment by Lassebq** [comment]
I'm using Windows 7, used java 17 to compile, Eclipse IDE. I don't have this issues when running it without debug mode, it opens the window like it does when double-clicking the jar.

**Comment by jredfox** [comment]
@Lassebq there is your problem. do not use java 17 on windows 7 it won't work with anything. java 8 - 9 causes crashes java 9 - 17 will probably cause crashes due to changes. 

use java 8 on windows 7 use latest commit to compile doubt it's stable. then report issues. I recommend only using released. I use commits as literally backups and progress reports to see changes helps prevent lots of bugs down the road.

**Comment by Lassebq** [comment]
Just tried it with java 8 Build 301. Same error.

**Comment by jredfox** [comment]
Ok try debug without calling openterminal does it have the same error

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lassebq** [comment]
No, it works perfectly fine when OpenTerminal isn't used

**Comment by jredfox** [comment]
Make sure the eclipse build run and your Java version on your PC all say 8 when running. Print the Java version in the Java program to make sure

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lassebq** [comment]
![image](https://user-images.githubusercontent.com/68742864/149819193-8d4f6cd7-9d24-4f4d-9aa8-e458cfe913fe.png)

**Comment by jredfox** [comment]
it's actually `properties.getProperty("java.version")` but, i see it's should be jdk 1.8. @Lassebq test https://github.com/jredfox/OpenTerminal/releases/tag/selfcmd-2.2.1

**Comment by jredfox** [comment]
also to confirm OpenTerminal is designed to be the main method of the program it calls system.exit and reboots with a terminal application. Which may be problematic if you are using it from another main method I see now.

**Comment by jredfox** [comment]
if you need further assistance https://discord.gg/qdewa8E

**Comment by jredfox** [comment]
fixed as of the re-design. You can run the terminal with debug mode enabled. I will need to re-test when ICP comes into effect and debugging but other then that should be good
