### ISSUE TITLE
Scroll wheel can't be used on Windows 7

### ISSUE THREAD

**Issue by Lassebq** [jredfox/OpenTerminal#42]
Although it seems to work on Windows 10, scrolling wheel won't scroll through console output, only scrollbar works.

**Comment by jredfox** [comment]
not reproducable as you don't have any information. All OpenTerminal does is open your native terminal unless it fails then it trys the broken JConsole. if it doesn't say JConsole it should work. does the command prompt work with scrolling with opening cmd normally?

**Comment by jredfox** [comment]
Try this:
Use Java 8 latest release
use the command `java -jar file.jar`

if that command itself doesn't work or has the same issues it's not an issue with OpenTerminal. all Openterminal does is open your native command prompt terminal with JVM virtual machine using `java -jar` command

**Comment by Lassebq** [comment]
Yes, `start "Test App" java -jar file.jar` gives the same result - scroll wheel does nothing. It was just weird that it works in default `cmd.exe` but not in start command, Thanks for clarifying.

**Comment by jredfox** [comment]
Try compiling Java 17 app with no open terminal and running that command

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
